---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: tg-3
    flagValue: false
