---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: booleanFlagRomain

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: rox.screen_width
          operator: ne
          operands:
            - 123
    flagValue: false
  - allOf:
      - property:
          name: rox.screen_width
          operator: eq
          operands:
            - 123
    flagValue: true
  - allOf:
      - flag:
          name: enableTutorialRomain
          value: "false"
    flagValue: false
  - allOf:
      - anyOf:
          - group:
              name: t
          - group:
              name: tg-1
    flagValue: false
